### ISSUE TITLE
Autoscaler workflow

### ISSUE THREAD

**Issue by oeway** [aicell-lab/autoscaler#8]
## Initialization

 * Start by running `start.sh` on a slurm cluster
 * A hypha service will be registered, and start a ray head node ( start with 0 worker node)
 * If a user send a request via the hypha service, the code be submitted as a ray task
 * We scan the head node to check the status to see if number of pending task
 
## Upscaling
 * If we see we have more pending task than available worker, then we spin up new workers by submitting Slurm jobs ( for 10 mintues), no new worker will be created if it hit the max_worker number.
 * once the worker joined the cluster, ray will process the pending. 
 * The hypha service then retrieves the reults

## Downscaling
 * We have a scanning code, which will check the status of workers and pending tasks, if there are no pending tasks, then we will shutdown the worker nodes.
 * There a parameter for configure the min_worker node (TODO: @marcus1337 ) can be 0.

Note:
 - Time to create new worker (e.g. a few seconds, upto 1 minutes)
 - Delay to shutdown the worker (@marcus1337 ), we need to set a parameter to delay the shutdown to smooth the up and down, and also make sure we reset the timer once there is new request.

@marcus1337 Please add these to the readme.

**Comment by marcus1337** [comment]
[config.py](https://github.com/aicell-lab/autoscaler/blob/dev/autoscaler/config.py) `ZOMBIE_TIMEOUT` is used as timeout when downscaling worker nodes.

**Comment by marcus1337** [comment]
README updated in this [commit](https://github.com/aicell-lab/autoscaler/commit/b67a90a1b7165cab148eb2708101d20d8576b25b).
